config/routes.rb
# -*- encoding : utf-8 -*-
AuthenticationUser::Engine.routes.draw do
  resources :basket_items, only: [:create, :update, :destroy]
  resources :baskets, only: [:index, :show, :destroy] do
    get :info, on: :member
    get :registration, on: :member
    post :thanks, on: :member
    # post 'change_status/:status', on: :member, to: 'baskets#change_status', as: :change_status
    get :send_order, on: :collection
    get :list, on: :collection
    get :report, on: :collection
  end

  get 'registration', to: 'users#new', as: :registration
  get 'login', to: 'user_sessions#new', as: :login
  get 'login_ynd', to: 'user_sessions#new', as: :login_ynd, defaults: { provider: 'yandex' }
  get 'login_mail', to: 'user_sessions#new', as: :login_mail, defaults: { provider: 'mailru' }
  get 'logout', to: 'user_sessions#destroy', as: :logout
  resources :users do
    get :activate, on: :member
    post :create_from_cart, on: :collection
  end
  get 'edit_password_reset/:id', to: 'password_resets#edit'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  resources :password_resets, expect: [:index, :show, :delete]
  resources :user_sessions
end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  before_save :set_defaults
  before_validation :convert_requisites#, unless: @legal_hash.blank?

  attr_accessible :legal, :fio, :email, :phone, :address, :password, :role,
    :with_message, :password_confirmation, :remember_me, :without_pass, :authentications_attributes
  attr_accessor :with_message, :without_pass

  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :authentications, dependent: :destroy
  has_many :baskets, dependent: :destroy
  accepts_nested_attributes_for :authentications

  validates_presence_of :email, :fio
  validates_uniqueness_of :email
  validates :email, format: {  with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})/,
                               message: 'неверный формат! верно, например, mail@temsys.ru' }, allow_blank: true
  validates :phone, format: { with: /\A[+]?[78]?\s?[\s|(]?\d{3}[\s|)]?\s?\d{3}[-|\s]?\d{2}[-|\s]?\d{2}\z/,
                              message: 'видимо вы ошиблись в написании телефона' }, allow_blank: true
  validates_length_of :fio, :email, :address, maximum: 250
  validates_length_of :with_message, maximum: 500
  validates_length_of :password, minimum: 5, allow_blank: true
  validates_confirmation_of :password
  validate :valid_requisites, unless: :new_record?
  validate :without_password, if: :new_record?

  scope :ordering, -> { order(:fio) }

  ROLES = %w[admin manager user]
  LEGAL = { ru: [[0, 'Физическое лицо'],[1, 'Юридическое лицо']],
            en: [[0, 'Individual'],[1, 'Legal entity']] }

  def self.filter_query_get(params)
    if params[:column_name] == 'id'
      self.where(id: params[:value]).ordering
    else
      arel = self.arel_table
      attr = arel[params[:column_name]]
      self.where(attr.matches("%#{params[:value]}%")).ordering
    end
  end

  def to_s
    email
  end

  def content_name
    email
  end

  def admin?
    role == "admin".freeze
  end

  def admin_less?
    role == "admin_less".freeze || role == "admin".freeze
  end

  def manager?
    role != 'user' && (role == 'manager' || role == 'admin' || role == 'admin_less')
  end

  def user?
    role == 'user'
  end

  def legal_hash_set(params)
    @legal_hash ||= Hash.new
    %w[inn kpp ogrn bank bic correspondent_account checking_account].each do |field|
      if params.has_key?(field.to_s)
        @legal_hash.merge!(field.to_sym => params[field.to_s])
      end
    end
  end

  def inn
    (@legal_hash || legal_hash_get)[:inn]
  end

  def kpp
    (@legal_hash || legal_hash_get)[:kpp]
  end

  def ogrn
    (@legal_hash || legal_hash_get)[:ogrn]
  end

  private

  def bank
    (@legal_hash || legal_hash_get)[:bank]
  end

  def bic
    (@legal_hash || legal_hash_get)[:bic]
  end

  def correspondent_account
    (@legal_hash || legal_hash_get)[:correspondent_account]
  end

  def checking_account
    (@legal_hash || legal_hash_get)[:checking_account]
  end

  def valid_requisites
    if self.legal && role == 'user'
      %w[inn kpp ogrn bank bic correspondent_account checking_account].each do |field|
        if self.send(field).blank?
          errors.add(field.to_sym, I18n.t(:blank, scope: [:activerecord, :errors, :models, :user,
                                                          :attributes, field.to_sym]))
        end
      end
    end
  end

  def without_password
    if !self.without_pass && self.password.blank?
      errors.add(field.to_sym, I18n.t(:blank, scope: [:activerecord, :errors, :models, :user,
                                                      :attributes, :password]))
    end
  end

  def set_defaults
    self.role = "user" if role.blank?
  end

  def convert_requisites
    self.info = @legal_hash.to_s
  end

  def legal_hash_get
    #{ :inn => '' }
    if info.is_a? Hash
      @legal_hash = info
    else
      @legal_hash = {}
      hash_from_info =  Hash[(info.gsub(/[{}\\]/,'')||'').split(",").collect{|x| x.strip.split("=>")}]
      %w[inn kpp ogrn bank bic correspondent_account checking_account].each do |field|
        value = hash_from_info[":#{field}"].strip[1..-2] if hash_from_info.has_key?(":#{field}")
        @legal_hash.merge!(field.to_sym => (value || ''))
      end
    end
    @legal_hash
  end
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:index, :new, :create, :activate]
  before_filter :set_actions, if: proc { request.format.symbol == :html && current_user&.admin_less? }

  def index
    if current_user&.admin?
      @list_pages = Admin::ListPages.new do |l|
        l.controller_name = controller_name
        l.action_name = action_name
        l.list = User.ordering.page(params[:page])
      end
      render 'admin_index'
    else
      raise ExceptionsErrors::AuthenticationError.new
    end
  end

  def show
    if current_user
      @user = User.find(params[:id])
      if !current_user.manager? && @user.id != current_user.id
        raise ExceptionsErrors::InvalidAccountAccess.new
      end
    else
      raise ExceptionsErrors::AuthenticationError.new
    end
  end

  def new
    @user = User.new
    respond_to do |format|
      format.html { render 'new_edit' }
      format.js
    end
  end

  def edit
    if current_user
      @user = User.find(params[:id])
      if !current_user.admin_less? && @user.id != current_user.id
        raise ExceptionsErrors::InvalidAccountAccess.new
      end
      render 'new_edit', locals: { form_partial: 'form_update' }
    else
      raise ExceptionsErrors::AuthenticationError.new
    end
  end

  def create
    raise LackAuthorityError if current_user&.user?
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        redir = current_user&.admin_less? ? authentication_user.users_path : :root
        format.html { redirect_to redir, notice: view_context.h_flash_msg(:activate) }
      else
        format.html { render action: 'new', template: '/application/new_edit' }
      end
    end
  end

  def create_from_cart
    raise LackAuthorityError if current_user&.user?
    @user = User.new(fio: params[:user][:fio], email: params[:user][:email], without_pass: true)

    basket_id = session[:basket_id]
    respond_to do |format|
      if @user.save

        @user.activate!
        @user.update_attributes(password: params[:user][:password], password_confirmation: params[:user][:password])
        login(@user.email, params[:user][:password])

        session[:basket_id] = basket_id
        @current_basket.update_attributes!(
          name: @user.fio || 'Покупатель',
          contacts: @user.email,
          address: @user.address,
          user_id: @user.id,
          without_check: true
        )
        format.html { redirect_to authentication_user.info_basket_path(id: basket_id) }
      else
        format.html { render '/baskets/registration' }
      end
    end
  end

  def update
    if current_user
      @user = User.find(params[:id])
      if !current_user.manager? && @user.id != current_user.id
        raise ExceptionsErrors::InvalidAccountAccess.new
      end
      @user.legal_hash_set(params)

      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to authentication_user.user_path(@user), notice: view_context.h_flash_msg(:update) }
        else
          @user.legal_hash_set(params)
          format.html { render action: 'edit', template: '/application/new_edit', locals: { form_partial: 'form_update' } }
        end
      end
    else
      raise ExceptionsErrors::AuthenticationError.new
    end
  end

  def destroy
    if current_user
      @user = User.find(params[:id])
      @user.destroy

      respond_to do |format|
        format.html { redirect_to authentication_user.users_url }
      end
    else
      raise ExceptionsErrors::AuthenticationError.new
    end
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      redirect_to(login_path, notice: view_context.h_flash_msg(:successe))
    else
      not_authenticated
    end
  end

  private

  def set_actions
    @user = User.find(params[:id]) if params[:id]
    @admin_panel = Admin::Panel::Base.new(@user || User, { namespace: ''})
    @admin_panel.from(controller_name, action_name)
    @admin_panel.model_engine = 'authentication_user'
  end
end

app/views/users/_form.html.erb
<% form_with_terms = config_get('main', 'terms_of_service') %>
<% css_class = form_with_terms ? 'form-login js__form-with-terms' : 'form-login' %>

<%= form_for(@user, url: authentication_user.users_path, html: { class: css_class }, validate: true) do |f| %>
  <%= render "form_errors", object: f.object %>

  <div class="path-10 clfl">
    <%= f.label :fio, class:'login-label' %>
    <%= f.text_field :fio, class:'login-input' %>

    <%= f.label :email, class:'login-label' %>
    <%= f.text_field :email, class:'login-input' %>
  </div>

  <div class="path-4 padd-r">
    <%= f.label :password, class:'login-label' %>
    <%= f.password_field :password, class:'login-input' %>
  </div>
  <div class="path-4">
    <%= f.label :password_confirmation, class:'login-label' %>
    <%= f.password_field :password_confirmation, class:'login-input' %>
  </div>
  <div class='clearfloat'></div>

  <% if form_with_terms %>
    <div class="path-10 marg-tb">
      <div class='terms-of-service-cnt template-form-notice'>
        <%= check_box_tag :terms_of_service, 0, false, class: 'terms-of-service js__terms-of-service' %>
        <%= label_tag :terms_of_service, I18n.t(:terms_of_service, scope: 'attributes'), class: 'terms-of-service'%>
        <div class='field_with_errors'>
          <span class='js__terms-of-service-error message'></span>
        </div>
      </div>
    </div>
    <div class='clearfloat'></div>
  <% end %>

  <div class="path-3">
    <%= f.submit t('views.form.new_user'), class: 'login-button' %>
  </div>

  <div class='path-7'>
    <p class='small-txt'>
      На указанную электронную почту будет выслано письмо для подтверждения регистрации.
    </p>
  </div>
  <div class='clearfloat'></div>
<% end %>

app/views/users/_form_update.html.erb
<%= form_for(@user, url: authentication_user.user_path(@user), html: { class: 'wrap form-add js__template-system' }, validate: true) do |f| %>
  <%= render "form_errors", object: f.object %>

  <div class='path-7 clfl'>
    <% if current_user.admin_less? %>
      <%= f.label :legal, class:'f-label' %>
      <%= f.collection_select(:legal, User::LEGAL[I18n.locale], :first, :last, {}, class:'f-input') %>
    <% end %>

    <%= f.label :fio, class:'f-label' %>
    <%= f.text_field :fio, class:'f-input' %>
  </div>
  <div class='clearfloat'></div>

  <div class='path-5 padd-r clfl'>
    <%= f.label :email, class:'f-label' %>
    <%= f.text_field :email, class:'f-input' %>
  </div>
  <div class='path-2 clfl'>
    <%= f.label :phone, class:'f-label' %>
    <%= f.text_field :phone, class:'f-input' %>
  </div>
  <div class='clearfloat'></div>

  <div class='path-7'>
    <%= f.label :address, class:'f-label' %>
    <%= f.text_area :address, class:'f-area' %>

    <%= render('legal_edit', f: f.object) if @user.legal %>

    <%= submit_tag(t('users.actions.update'), class:'f-button') unless current_user.admin_less?  %>
  </div>

  <div class='half padd-l'>
  </div>
  <div class='clearfloat'></div>

  <% if current_user.admin? %>
    <%= render "danger_block", f: f, options: [
      { field: :role, field_type: :collection_select, collection: User::ROLES,
        value_method: :to_s, text_method: :humanize, field_css_class: "f-a-input" }]
      %>
  <% end %>
<% end %>

app/views/users/_index_table_row.html.erb
<tr>
  <td class='td-link'><%= link_to index_table_row.id, authentication_user.user_path(index_table_row), class:'order-link' %></td>
  <td><%= index_table_row.fio %></td>
  <td><%= index_table_row.email %></td>
  <td><%= index_table_row.phone %></td>
  <td><%= index_table_row.address %></td>
</tr>

app/views/users/_legal.html.erb
<% %w[inn kpp ogrn bank bic correspondent_account checking_account].each do |field| %>
  <%= content_tag(:span, t(field.to_sym, scope: [:activerecord, :attributes, :user]), class: 'user-label') %>
  <span class='user-value'>
  	<%= @user.send(field) %>
  </span>
<% end %>

app/views/users/_legal_edit.html.erb
<div class="half padd-r">
	<%= label_tag :inn, t(:inn, scope: [:activerecord, :attributes, :user]), class:'user-label' %>
	<%= text_field_tag :inn, f.inn, class:'user-input' %>
</div>

<div class="half padd-l">
	<%= label_tag :kpp, t(:kpp, scope: [:activerecord, :attributes, :user]), class:'user-label' %>
	<%= text_field_tag :kpp, f.kpp, class:'user-input' %>
</div>
<div class="clearfloat"></div>

<%= label_tag :ogrn, t(:ogrn, scope: [:activerecord, :attributes, :user]), class:'user-label' %>
<%= text_field_tag :ogrn, f.ogrn, class:'user-input' %>

<%= label_tag :bank, t(:bank, scope: [:activerecord, :attributes, :user]), class:'user-label' %>
<%= text_field_tag :bank, f.bank, class:'user-input' %>

<%= label_tag :bic, t(:bic, scope: [:activerecord, :attributes, :user]), class:'user-label' %>
<%= text_field_tag :bic, f.bic, class:'user-input' %>

<div class="half padd-r">
	<%= label_tag :correspondent_account, t(:correspondent_account, scope: [:activerecord, :attributes, :user]), class:'user-label' %>
	<%= text_field_tag :correspondent_account, f.correspondent_account, class:'user-input' %>
</div>

<div class="half padd-l">
	<%= label_tag :checking_account, t(:checking_account, scope: [:activerecord, :attributes, :user]), class:'user-label' %>
	<%= text_field_tag :checking_account, f.checking_account, class:'user-input' %>
</div>
<div class="clearfloat"></div>

app/views/users/index.html.erb
<%= provide :h1, content_tag(:h1, t("#{params[:controller]}.#{params[:action]}.header_h1"), class: config_get('html', 'h1_class')) %>

<div class='page-bg'>
	<table class='order-table' data-table-filter='users'>
		<tr>
			<th class='td-link' data-table-filter-name='id'>
				<span class='th-span'>Номер</span>
			</th>
      <th class='td-message' data-table-filter-name='fio'>
        <span class='th-span'>Организация/ФИО</span>
      </th>
      <th class='td-message' data-table-filter-name='email'>
        <span class='th-span'>Элек.почта</span>
      </th>
      <th data-table-filter-name='phone'>
        <span class='th-span'>Телефон</span>
      </th>
      <th class='td-message' data-table-filter-name='address'>
        <span class='th-span'>Адрес</span>
      </th>
      <th><span class='th-span'>Скидка</span></th>
		</tr>
	  <%= render partial: 'index_table_row', collection: @users %>
  </table>
</div>

app/views/users/new.js.erb
$.magnificPopup.open({
  items: {
    src: '<%=j render "form" %>',
    type: 'inline',
    closeBtnInside: true
  },
  closeOnBgClick: false
});

$('.mfp-content').addClass('magnific-container modal-form')
$('.mfp-content').find('form').addClass('magnific-form')
$('.mfp-content').find('form').prepend('<div class="magnific-title">Регистрация на сайте</div>')
$('form.magnific-form').enableClientSideValidations();
formWithTerms();

app/views/users/show.html.erb
<%= provide :h1, content_tag(:h1, t("#{params[:controller]}.#{params[:action]}.header_h1"), class: config_get('html', 'h1_class')) %>
<%= provide :stylesheets, stylesheet_link_tag(:user, media: :all) %>

<div class='content-wrap clfl'>
  <div class='path-6'>
    <% %w[fio email phone address].each do |field| %>
      <%= content_tag(:span, t(field, scope: [:activerecord, :attributes, :user]), class:'f-label') %>
      <span class='f-value'>
        <%= @user.send(field.to_sym) %>
      </span>
    <% end %>

    <%= render('legal', f: @user) if @user.legal %>

    <% if current_user.admin_less? || current_user == @user %>
      <div class='path-5'>
        <%= link_to t('users.actions.edit'), authentication_user.edit_user_path(@user), class:'f-button' %>
      </div>
    <% end %>
  </div>

  <div class='path-6'>
    <%# <%= link_to t('users.actions.orders'), list_baskets_path, class:'order-button marg-b' %>
    <%= content_tag :span, t('users.actions.orders'), class:'order-button marg-b' %>
    <table class='order-table'>
      <tr>
        <th class='td-link'>
          <span class='th-span'>Номер</span>
        </th>
        <th><span class='th-span'>Дата</span></th>
        <th><span class='th-span'>Сумма</span></th>
        <th><span class='th-span'>Статус</span></th>
      </tr>
      <% Basket.last_baskets(@user.id, 2).each do |basket| %>
        <tr>
          <td class='td-link'><%= link_to basket.id, authentication_user.basket_path(basket), class:'order-link' %></td>
          <td><%= l basket.created_at, format: :date_simple %></td>
          <td><%= basket.total_sum %></td>
          <td><%= basket.status_humanize %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>